In [4]:
file_name = '../text.txt'
file = open(file_name, mode = 'r')
lines = file.readlines()
lines[0].split()

['Text',
 'mining,also',
 'referred',
 'to',
 'as',
 'text',
 'data',
 'mining,',
 'similar',
 'to',
 'text',
 'analytics,',
 'is',
 'the',
 'process',
 'of',
 'deriving',
 'high-quality',
 'information',
 'from',
 'text.']

In [2]:
lines[0].upper()

'   TEXT MINING,ALSO REFERRED TO AS TEXT DATA MINING, SIMILAR TO TEXT ANALYTICS, IS THE PROCESS OF DERIVING HIGH-QUALITY INFORMATION FROM TEXT.\n'

In [3]:
lines[0].title()

'   Text Mining,Also Referred To As Text Data Mining, Similar To Text Analytics, Is The Process Of Deriving High-Quality Information From Text.\n'

In [4]:
lines[0].strip()

'Text mining,also referred to as text data mining, similar to text analytics, is the process of deriving high-quality information from text.'

In [5]:
lines[0].startswith("Text")

False

In [6]:
txt = "as, apple, banana, cherry"

x = txt.rsplit(", ")

print(x)

['as', 'apple', 'banana', 'cherry']


In [7]:
file = open(file_name, mode = 'r')
texts = file.read()
texts

'   Text mining,also referred to as text data mining, similar to text analytics, is the process of deriving high-quality information from text.\nIt involves "the discovery by computer of new, previously unknown information, by automatically extracting information from different written resources.\n"[1] Written resources may include websites, books, emails, reviews, and articles. High-quality information is typically obtained by devising patterns and trends by means such as statistical pattern learning. \nAccording to Hotho et al. (2005) we can differ three different perspectives of text mining: information extraction, data mining, and a KDD (Knowledge Discovery in Databases) process.\n[2] Text mining usually involves the process of structuring the input text (usually parsing, along with the addition of some derived linguistic features and the removal of others, and subsequent insertion into a database), deriving patterns within the structured data.'

In [8]:
texts.splitlines()

['   Text mining,also referred to as text data mining, similar to text analytics, is the process of deriving high-quality information from text.',
 'It involves "the discovery by computer of new, previously unknown information, by automatically extracting information from different written resources.',
 '"[1] Written resources may include websites, books, emails, reviews, and articles. High-quality information is typically obtained by devising patterns and trends by means such as statistical pattern learning. ',
 'According to Hotho et al. (2005) we can differ three different perspectives of text mining: information extraction, data mining, and a KDD (Knowledge Discovery in Databases) process.',
 '[2] Text mining usually involves the process of structuring the input text (usually parsing, along with the addition of some derived linguistic features and the removal of others, and subsequent insertion into a database), deriving patterns within the structured data.']

In [9]:
with open(file_name, mode = 'r') as file1:
    Lines = file1.readlines()
    count = 0
    # Strips the newline character
    for line in Lines:
        count += 1
        print("Line{}: {}".format(count, line.strip()))

Line1: Text mining,also referred to as text data mining, similar to text analytics, is the process of deriving high-quality information from text.
Line2: It involves "the discovery by computer of new, previously unknown information, by automatically extracting information from different written resources.
Line3: "[1] Written resources may include websites, books, emails, reviews, and articles. High-quality information is typically obtained by devising patterns and trends by means such as statistical pattern learning.
Line4: According to Hotho et al. (2005) we can differ three different perspectives of text mining: information extraction, data mining, and a KDD (Knowledge Discovery in Databases) process.
Line5: [2] Text mining usually involves the process of structuring the input text (usually parsing, along with the addition of some derived linguistic features and the removal of others, and subsequent insertion into a database), deriving patterns within the structured data.


In [19]:
import re
re.search("^   Text mining", texts)

<re.Match object; span=(0, 14), match='   Text mining'>

In [12]:
txt = "The rain in Spain"
x = re.split("\s", txt)
print(x)

['The', 'rain', 'in', 'Spain']


In [17]:
txt = "That will be 519 519 dollars"

#Find all digit characters:

x = re.findall("\d+", txt)
print(x)

['519', '519']


In [20]:
txt = "The rain in Spain"
x = re.split("\s", txt, 1)
print(x)

['The', 'rain in Spain']


In [21]:
txt = "The rain in Spain"
x = re.sub("\s", "_", txt)
print(x)

The_rain_in_Spain


In [29]:
txt = "The rain in Spainmlkfdlkfldkfldfldf"

#Find all lower case characters alphabetically between "a" and "m":

x = re.findall("[a-m]", txt)
print(x)


['h', 'e', 'a', 'i', 'i', 'a', 'i', 'm', 'l', 'k', 'f', 'd', 'l', 'k', 'f', 'l', 'd', 'k', 'f', 'l', 'd', 'f', 'l', 'd', 'f']


In [34]:
txt = "The rain in 559 5 Spainmlkfdlkfldkfldfldf"

#Find all lower case characters alphabetically between "a" and "m":

x = re.findall("\d+", txt)
print(x)

['559', '5']


In [45]:

txt = "5555The 555rai n555 in Spain"

#Return a match at every word character (characters from a to Z, digits from 0-9, and the underscore _ character):

x = re.findall("\w+", txt)

print(x)

['5555The', '555rai', 'n555', 'in', 'Spain']


In [49]:
txt = "8 times before 11:45 AM"

#Check if the string has any characters from a to z lower case, and A to Z upper case:

x = re.findall("[a-zA-Z]", txt)
x

['t', 'i', 'm', 'e', 's', 'b', 'e', 'f', 'o', 'r', 'e', 'A', 'M']

In [5]:
file_name1 = '../mnist.txt'
file1 = open(file_name1, mode = 'r')
file1.read()

'1,2,3,4,5,5,5,6,4,4,4,4'

In [6]:
import numpy as np
file_np = np.loadtxt('../mnist.txt', delimiter = ',')
file_np

array([1., 2., 3., 4., 5., 5., 5., 6., 4., 4., 4., 4.])

In [54]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [56]:
np.array([[1,0,0],[0,1,0],[0,0,1]])

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [60]:
np.random.rand(3,3)

array([[0.49268568, 0.46014352, 0.88710798],
       [0.1922293 , 0.03729845, 0.57278469],
       [0.8539719 , 0.19119267, 0.72706398]])